import type { IRocketChatRecord, IUser, IRoom } from "@rocket.chat/core-typings"

export type FieldType =
    | "TEXT"
    | "TEXTAREA"
    | "NUMBER"
    | "DATE"
    | "DATE_TIME"
    | "SELECT"
    | "MULTI_SELECT"
    | "USER"
    | "CHECKBOX"
    | "URL"
    | "FILE"
    | "FILE_MULTIPLE"
    | "DOCUMENT"
    | "ASSIGNEE"
    | "DEADLINE"

export interface IFieldDefinition {
    _id: string
    name: string
    type: FieldType
    options?: { _id: string; value: string; color?: string; order?: number }[]
    order: number
}

export interface IList extends IRocketChatRecord {
    name: string
    roomId: IRoom["_id"]
    key: string
    description?: string
    fieldDefinitions: IFieldDefinition[]
    hiddenFields?: string[]
    hiddenStages?: string[]
    hideEmptyGroups?: boolean
    templateKey?: string
    templateListKey?: string
    itemCount?: number
    createdAt: Date
    createdBy?: Pick<IUser, "_id" | "username" | "name">
    updatedBy?: Pick<IUser, "_id" | "username" | "name">
}

export interface IStage extends IRocketChatRecord {
    name: string
    listId: IList["_id"]
    order: number
    color: string
    templateStageKey?: string
    owner?: string
}

export interface ICustomFieldValue {
    fieldId: IFieldDefinition["_id"]
    value: any // Value of any type, depending on the `type` of the field
}

export interface IItem extends IRocketChatRecord {
    name?: string
    key: string
    description?: string
    listId: IList["_id"]
    stageId: IStage["_id"]
    order: number
    parentId?: IItem["_id"]
    customFields: ICustomFieldValue[]
    templateItemKey?: string
    generatingFields?: string[] // Field IDs that are currently being generated by AI
    createdBy?: Pick<IUser, "_id" | "username" | "name">
    createdAt: Date
    updatedBy?: Pick<IUser, "_id" | "username" | "name">
}

export interface IDocumentVersion {
    version: number
    content: string
    createdAt: Date
    createdBy: Pick<IUser, "_id" | "username" | "name">
}

export interface IDocument extends IRocketChatRecord {
    title: string
    content: string
    description?: string
    roomId: IRoom["_id"]
    versions: IDocumentVersion[]
    currentVersion: number
    templateKey?: string
    templateDocumentKey?: string
    createdAt: Date
    createdBy?: Pick<IUser, "_id" | "username" | "name">
    updatedAt: Date
    updatedBy?: Pick<IUser, "_id" | "username" | "name">
}

export interface IRoom extends IRocketChatRecord {
    _id: RoomID
    t: RoomType
    name?: string
    fname?: string
    msgs: number
    default?: boolean
    broadcast?: true
    featured?: true
    announcement?: string
    joinCodeRequired?: boolean
    announcementDetails?: {
        style?: string
    }
    encrypted?: boolean
    topic?: string
    reactWhenReadOnly?: boolean
    sysMes?: MessageTypesValues[] | boolean
    u: Pick<IUser, "_id" | "username" | "name">
    uids?: Array<string>
    lastMessage?: IMessage
    lm?: Date
    usersCount: number
    callStatus?: CallStatus
    webRtcCallStartTime?: Date
    servedBy?: {
        _id: string
    }
    prid?: string
    avatarETag?: string
    teamMain?: boolean
    teamId?: string
    teamDefault?: boolean
    open?: boolean
    autoTranslateLanguage?: string
    autoTranslate?: boolean
    unread?: number
    alert?: boolean
    hideUnreadStatus?: boolean
    hideMentionStatus?: boolean
    muted?: string[]
    unmuted?: string[]
    usernames?: string[]
    ts?: Date
    cl?: boolean
    ro?: boolean
    favorite?: boolean
    archived?: boolean
    description?: string
    createdOTR?: boolean
    e2eKeyId?: string
    federated?: boolean
    customFields?: Record<string, any>
    usersWaitingForE2EKeys?: {
        userId: IUser["_id"]
        ts: Date
    }[]
    sidepanel?: {
        items: [SidepanelItem, SidepanelItem?]
    }
    /**
     * @deprecated Using `boolean` is deprecated. Use `number` instead.
     */
    rolePrioritiesCreated?: number | boolean
}
